[package]
name = "highly_sendable"
version = "0.3.0-beta"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Sendable objects that can assist with communicating progress and status within your programme and beyond."
repository = "https://github.com/coruscateor/highly_sendable"
homepage = "https://coruscateor.com/projects/highly-sendable"
keywords = ["send", "result", "text", "progress", "status"]
authors = ["Paul Saunders"]
rust-version = "1.95.0"

[dependencies]

delegate = "0.13.5"

serde = { version = "1.0.229", features = ["derive"], optional = true }

corlib = { version = "0.5.0", optional = true }

accessorise = "0.3.0"

#accessorise = { path = "../accessorise" } //Do not remove

pastey = "0.2.3"

inc_dec = "0.2.0"

bytes = { version = "1.12.1", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

